In [37]:
import pandas as pd

In [38]:
r_data = pd.DataFrame()
for i  in range(12,23):
    tmp = pd.read_csv("C:/WORK/temp데이콘/data/rf_data/rf_20"+ str(i) +".csv")
    r_data=pd.concat([r_data, tmp])
r_data.reset_index().drop(labels="index", axis=1, inplace = True)
r_data

ymdhm  rf_10184100  rf_10184110  rf_10184140
0      2012-05-01 00:00          0.0          0.0          0.0
1      2012-05-01 00:10          0.0          0.0          0.0
2      2012-05-01 00:20          0.0          0.0          0.0
3      2012-05-01 00:30          0.0          0.0          0.0
4      2012-05-01 00:40          0.0          0.0          0.0
...                 ...          ...          ...          ...
11371  2022-07-18 23:10          0.0          0.0          0.0
11372  2022-07-18 23:20          0.0          0.0          0.0
11373  2022-07-18 23:30          0.0          0.0          0.0
11374  2022-07-18 23:40          0.0          0.0          0.0
11375  2022-07-18 23:50          0.0          0.0          0.0

[276336 rows x 4 columns]

In [39]:
w_data = pd.DataFrame()
for i  in range(12,23):
    tmp = pd.read_csv("C:/WORK/temp데이콘/data/water_data/data_20"+ str(i) +".csv")
    w_data=pd.concat([w_data, tmp])
w_data.reset_index().drop(labels="index", axis=1, inplace = True)
w_data

ymdhm     swl     inf     sfw   ecpc  tototf  tide_level  \
0      2012-05-01 00:00  24.800  555.00  219.07  24.93  555.00       445.0   
1      2012-05-01 00:10  24.794  464.60  218.86  25.15  562.90       449.0   
2      2012-05-01 00:20  24.789  478.10  218.69  25.31  576.40       451.0   
3      2012-05-01 00:30  24.789  464.80  218.69  25.31  563.10       452.0   
4      2012-05-01 00:40  24.789  478.10  218.69  25.31  576.40       450.0   
...                 ...     ...     ...     ...    ...     ...         ...   
11371  2022-07-18 23:10  25.040  259.23  212.86  31.14  259.23       510.0   
11372  2022-07-18 23:20  25.040  260.46  212.86  31.14  260.46       492.0   
11373  2022-07-18 23:30  25.040  259.37  212.86  31.14  259.37       475.0   
11374  2022-07-18 23:40  25.040  259.13  212.86  31.14  259.13       458.0   
11375  2022-07-18 23:50  25.040  258.16  212.86  31.14  258.16       442.0   

       wl_1018662  fw_1018662  wl_1018680  fw_1018680  wl_1018683  fw_1018683  \
0           310.7      469.05       300.2         0.0       290.0      729.80   
1           314.7      498.00       300.2         0.0       290.0      731.48   
2           313.7      490.68       301.2         0.0       290.0      726.42   
3           311.7      476.21       301.2         0.0       290.0      726.42   
4           311.7      476.21       301.2         0.0       291.0      707.17   
...           ...         ...         ...         ...         ...         ...   
11371         0.0      319.84         0.0         NaN         0.0     -456.41   
11372         0.0      314.01         0.0         NaN         0.0     -717.30   
11373         0.0      387.55         0.0         NaN         0.0     -843.37   
11374         0.0      454.91         0.0         NaN         0.0    -1023.37   
11375         0.0      582.21         0.0         NaN         0.0    -1049.44   

       wl_1019630  fw_1019630  
0           275.3      540.18  
1           275.3      540.18  
2           275.3      540.18  
3           276.3      552.17  
4           277.3      564.29  
...           ...         ...  
11371         0.0      974.40  
11372         0.0     1006.88  
11373         0.0     1039.90  
11374         0.0     1073.46  
11375         0.0     1090.45  

[276336 rows x 15 columns]

In [40]:
r_data2 = r_data.drop(labels='ymdhm', axis=1)
r_data2

rf_10184100  rf_10184110  rf_10184140
0              0.0          0.0          0.0
1              0.0          0.0          0.0
2              0.0          0.0          0.0
3              0.0          0.0          0.0
4              0.0          0.0          0.0
...            ...          ...          ...
11371          0.0          0.0          0.0
11372          0.0          0.0          0.0
11373          0.0          0.0          0.0
11374          0.0          0.0          0.0
11375          0.0          0.0          0.0

[276336 rows x 3 columns]

In [41]:
data = pd.concat([w_data, r_data2], axis=1)
data

ymdhm     swl     inf     sfw   ecpc  tototf  tide_level  \
0      2012-05-01 00:00  24.800  555.00  219.07  24.93  555.00       445.0   
1      2012-05-01 00:10  24.794  464.60  218.86  25.15  562.90       449.0   
2      2012-05-01 00:20  24.789  478.10  218.69  25.31  576.40       451.0   
3      2012-05-01 00:30  24.789  464.80  218.69  25.31  563.10       452.0   
4      2012-05-01 00:40  24.789  478.10  218.69  25.31  576.40       450.0   
...                 ...     ...     ...     ...    ...     ...         ...   
11371  2022-07-18 23:10  25.040  259.23  212.86  31.14  259.23       510.0   
11372  2022-07-18 23:20  25.040  260.46  212.86  31.14  260.46       492.0   
11373  2022-07-18 23:30  25.040  259.37  212.86  31.14  259.37       475.0   
11374  2022-07-18 23:40  25.040  259.13  212.86  31.14  259.13       458.0   
11375  2022-07-18 23:50  25.040  258.16  212.86  31.14  258.16       442.0   

       wl_1018662  fw_1018662  wl_1018680  fw_1018680  wl_1018683  fw_1018683  \
0           310.7      469.05       300.2         0.0       290.0      729.80   
1           314.7      498.00       300.2         0.0       290.0      731.48   
2           313.7      490.68       301.2         0.0       290.0      726.42   
3           311.7      476.21       301.2         0.0       290.0      726.42   
4           311.7      476.21       301.2         0.0       291.0      707.17   
...           ...         ...         ...         ...         ...         ...   
11371         0.0      319.84         0.0         NaN         0.0     -456.41   
11372         0.0      314.01         0.0         NaN         0.0     -717.30   
11373         0.0      387.55         0.0         NaN         0.0     -843.37   
11374         0.0      454.91         0.0         NaN         0.0    -1023.37   
11375         0.0      582.21         0.0         NaN         0.0    -1049.44   

       wl_1019630  fw_1019630  rf_10184100  rf_10184110  rf_10184140  
0           275.3      540.18          0.0          0.0          0.0  
1           275.3      540.18          0.0          0.0          0.0  
2           275.3      540.18          0.0          0.0          0.0  
3           276.3      552.17          0.0          0.0          0.0  
4           277.3      564.29          0.0          0.0          0.0  
...           ...         ...          ...          ...          ...  
11371         0.0      974.40          0.0          0.0          0.0  
11372         0.0     1006.88          0.0          0.0          0.0  
11373         0.0     1039.90          0.0          0.0          0.0  
11374         0.0     1073.46          0.0          0.0          0.0  
11375         0.0     1090.45          0.0          0.0          0.0  

[276336 rows x 18 columns]

In [42]:
train = data.iloc[:-24 * 6 * 48].drop(labels='ymdhm', axis = 1).reset_index(drop=True)
test = data.iloc[-24 * 6 * 48:].reset_index(drop=True)

In [43]:

X = train[['swl', 'inf', 'sfw', 'ecpc', 'tototf', 'tide_level','fw_1018662', 'fw_1018680', 'fw_1018683','fw_1019630', 'rf_10184100', 'rf_10184110','rf_10184140']] 
y_1 = train[['wl_1018662']]
y_2 = train[['wl_1018680']]
y_3 = train[['wl_1018683']]
y_4 = train[['wl_1019630']]

In [44]:
test_X = test[['swl', 'inf', 'sfw', 'ecpc', 'tototf', 'tide_level','fw_1018662', 'fw_1018680', 'fw_1018683','fw_1019630', 'rf_10184100', 'rf_10184110','rf_10184140']] 

In [45]:
X.fillna(X.mean(),inplace=True)
y_1.fillna(y_1.mean(),inplace=True)
y_2.fillna(y_2.mean(),inplace=True)
y_3.fillna(y_3.mean(),inplace=True)
y_4.fillna(y_4.mean(),inplace=True)

C:\Users\Cedric\AppData\Local\Temp\ipykernel_8816\1709116272.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.fillna(X.mean(),inplace=True)
C:\Users\Cedric\AppData\Local\Temp\ipykernel_8816\1709116272.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_1.fillna(y_1.mean(),inplace=True)
C:\Users\Cedric\AppData\Local\Temp\ipykernel_8816\1709116272.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

Se

In [46]:
test_X.fillna(X.mean(),inplace=True)

C:\Users\Cedric\AppData\Local\Temp\ipykernel_8816\3856101570.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_X.fillna(X.mean(),inplace=True)


from sklearn.model_selection import GridSearchCV
grid_cv = GridSearchCV(rf,
                       param_grid=params,
                       cv = kfold,
                       n_jobs=-1)

grid_cv.fit(X,y)

grid_cv.best_estimator_


model=grid_cv.best_estimator_
model.fit(X,y)
y_pred=model.predict(test_X)

y_pred

In [47]:
import keras
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, LSTM, GRU, AveragePooling1D, GlobalAveragePooling1D
from keras import models
from keras import layers
from keras import optimizers
from tensorflow.keras.optimizers import RMSprop,Adam
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from keras.models import load_model, save_model

In [48]:
#model생성
model = keras.Sequential([
    keras.layers.Dense(60, activation="relu"),
    keras.layers.Dense(1, activation="linear")
])

#model compile 설정
opt = tf.optimizers.RMSprop(0.001)
model.compile(optimizer=opt, loss="mse", metrics=['mae'])



In [49]:
model.fit(X,y_1, epochs=10, batch_size=128)
pred_1= model.predict(test_X)


Epoch 1/10
2105/2105 [==============================] - 3s 828us/step - loss: 2804.2017 - mae: 22.0388
Epoch 2/10
2105/2105 [==============================] - 2s 825us/step - loss: 592.8150 - mae: 11.2484
Epoch 3/10
2105/2105 [==============================] - 2s 825us/step - loss: 468.5323 - mae: 9.8660
Epoch 4/10
2105/2105 [==============================] - 2s 829us/step - loss: 384.5665 - mae: 8.6377
Epoch 5/10
2105/2105 [==============================] - 2s 827us/step - loss: 322.9143 - mae: 7.9743
Epoch 6/10
2105/2105 [==============================] - 2s 827us/step - loss: 270.2117 - mae: 7.2230
Epoch 7/10
2105/2105 [==============================] - 2s 825us/step - loss: 223.1270 - mae: 6.5292
Epoch 8/10
2105/2105 [==============================] - 2s 830us/step - loss: 201.1690 - mae: 6.0577
Epoch 9/10
2105/2105 [==============================] - 2s 832us/step - loss: 169.1354 - mae: 5.7046
Epoch 10/10
216/216 [==============================] - 0s 633us/step


In [50]:
pred_1

array([[280.67288],
       [281.86774],
       [285.12607],
       ...,
       [297.5417 ],
       [308.92755],
       [325.09186]], dtype=float32)

In [51]:
model.fit(X,y_2, epochs=10, batch_size=128)
pred_2= model.predict(test_X)
pred_2

Epoch 1/10
2105/2105 [==============================] - 2s 856us/step - loss: 174.0027 - mae: 7.6841
Epoch 2/10
2105/2105 [==============================] - 2s 844us/step - loss: 160.8698 - mae: 7.4217
Epoch 3/10
2105/2105 [==============================] - 2s 838us/step - loss: 143.4123 - mae: 7.1776
Epoch 4/10
2105/2105 [==============================] - 2s 1ms/step - loss: 138.6428 - mae: 7.0479
Epoch 5/10
2105/2105 [==============================] - 2s 922us/step - loss: 128.4221 - mae: 6.9551
Epoch 6/10
2105/2105 [==============================] - 2s 836us/step - loss: 119.6210 - mae: 6.7791
Epoch 7/10
2105/2105 [==============================] - 2s 837us/step - loss: 113.5252 - mae: 6.6744
Epoch 8/10
2105/2105 [==============================] - 2s 843us/step - loss: 106.6422 - mae: 6.5843
Epoch 9/10
2105/2105 [==============================] - 2s 855us/step - loss: 104.8530 - mae: 6.5336
Epoch 10/10
216/216 [==============================] - 0s 588us/step


array([[270.9736 ],
       [271.9912 ],
       [278.16055],
       ...,
       [300.7039 ],
       [306.99084],
       [314.02014]], dtype=float32)

In [52]:
model.fit(X,y_3, epochs=10, batch_size=128)
pred_3= model.predict(test_X)
pred_3

Epoch 1/10
2105/2105 [==============================] - 2s 839us/step - loss: 60.9879 - mae: 4.6105
Epoch 2/10
2105/2105 [==============================] - 2s 834us/step - loss: 58.4704 - mae: 4.5133
Epoch 3/10
2105/2105 [==============================] - 2s 829us/step - loss: 56.2534 - mae: 4.4649
Epoch 4/10
2105/2105 [==============================] - 2s 863us/step - loss: 53.5421 - mae: 4.4223
Epoch 5/10
2105/2105 [==============================] - 2s 828us/step - loss: 51.7672 - mae: 4.3879
Epoch 6/10
2105/2105 [==============================] - 2s 830us/step - loss: 50.5647 - mae: 4.3488
Epoch 7/10
2105/2105 [==============================] - 2s 830us/step - loss: 48.3221 - mae: 4.2841
Epoch 8/10
2105/2105 [==============================] - 2s 822us/step - loss: 47.7896 - mae: 4.2685
Epoch 9/10
2105/2105 [==============================] - 2s 836us/step - loss: 46.0228 - mae: 4.2029
Epoch 10/10
216/216 [==============================] - 0s 612us/step


array([[269.20746],
       [269.68094],
       [269.11008],
       ...,
       [301.09064],
       [305.9762 ],
       [312.729  ]], dtype=float32)

In [53]:
model.fit(X,y_4, epochs=10, batch_size=128)
pred_4= model.predict(test_X)
pred_4

Epoch 1/10
2105/2105 [==============================] - 2s 833us/step - loss: 35.9570 - mae: 3.3787
Epoch 2/10
2105/2105 [==============================] - 2s 828us/step - loss: 26.8317 - mae: 2.7672
Epoch 3/10
2105/2105 [==============================] - 2s 834us/step - loss: 25.9558 - mae: 2.6920
Epoch 4/10
2105/2105 [==============================] - 2s 829us/step - loss: 23.7505 - mae: 2.5581
Epoch 5/10
2105/2105 [==============================] - 2s 837us/step - loss: 22.6233 - mae: 2.5067
Epoch 6/10
2105/2105 [==============================] - 2s 830us/step - loss: 21.2713 - mae: 2.3799
Epoch 7/10
2105/2105 [==============================] - 2s 838us/step - loss: 19.5242 - mae: 2.2545
Epoch 8/10
2105/2105 [==============================] - 2s 838us/step - loss: 18.9994 - mae: 2.2207
Epoch 9/10
2105/2105 [==============================] - 2s 842us/step - loss: 18.1539 - mae: 2.2070
Epoch 10/10
216/216 [==============================] - 0s 672us/step


array([[265.9101 ],
       [263.89404],
       [260.26062],
       ...,
       [307.10062],
       [309.14365],
       [310.2578 ]], dtype=float32)

In [54]:
sample_submission = pd.read_csv("C:/WORK/temp데이콘/data/sample_submission.csv")

sample_submission["wl_1018662"] = pred_1
sample_submission["wl_1018680"] = pred_2
sample_submission["wl_1018683"] = pred_3
sample_submission["wl_1019630"] = pred_4
sample_submission.to_csv('8dang.csv', index=False)